services:
  nginx1:
    image: nginx:latest
    container_name: nginx1
    ports:
      - "8080:80"
    volumes:
      - ./TP-Final-3IW-ESGI:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php1

  nginx2:
    image: nginx:latest
    container_name: nginx2
    ports:
      - "8081:80"
    volumes:
      - ./TP-Final-3IW-ESGI:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php2

  php1:
    build:
      context: ./php
    container_name: php1
    volumes:
      - ./TP-Final-3IW-ESGI:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=tp_docker
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - SERVER_ID=Server_1
    depends_on:
      - mysql

  php2:
    build:
      context: ./php
    container_name: php2
    volumes:
      - ./TP-Final-3IW-ESGI:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=tp_docker
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - SERVER_ID=Server_2
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tp_docker
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf

  phpmyadmin: 
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql

volumes:
  db_data: