services:
  traefik:
    image: traefik
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Permet à Traefik d'interagir avec Docker
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml # Fichier de configuration de Traefik
      - ./traefik/certs:/certs # Emplacement des certificats SSL
    networks:
      - web

  certs_generator:
    image: alpine:latest
    container_name: certs_generator
    command: sh -c "apk add openssl && /scripts/generate-certs.sh"
    volumes:
      - ./traefik/certs:/etc/nginx/certs
      - ./scripts:/scripts

  nginx1:
    image: nginx:latest
    container_name: nginx1
    volumes:
      - ./app:/var/www/html
      - ./nginx/nginx1.conf:/etc/nginx/conf.d/default.conf
      - ./traefik/certs:/etc/nginx/certs
    networks: 
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.site1.rule=Host(`site1.local`)"
      - "traefik.http.routers.site1.entrypoints=websecure"
      - "traefik.http.routers.site1.tls=true"
      - "traefik.http.routers.site1.tls.domains[0].main=site1.local"
    depends_on:
      - php1
      - certs_generator

  nginx2:
    image: nginx:latest
    container_name: nginx2
    volumes:
      - ./app_second:/var/www/html
      - ./nginx/nginx2.conf:/etc/nginx/conf.d/default.conf
      - ./traefik/certs:/etc/nginx/certs
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.site2.rule=Host(`site2.local`)"
      - "traefik.http.routers.site2.entrypoints=websecure"
      - "traefik.http.routers.site2.tls=true"
      - "traefik.http.routers.site2.tls.domains[0].main=site2.local"
    depends_on:
      - php2
      - certs_generator

  php1:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php1
    volumes:
      - ./app:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=tp_docker
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - mysql
    networks:
      - web

  php2:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php2
    volumes:
      - ./app_second:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=tp_docker
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - mysql
    networks:
      - web

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tp_docker
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - web

  phpmyadmin: 
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pma.rule=Host(`pma.local`)"
      - "traefik.http.routers.pma.entrypoints=websecure"
      - "traefik.http.routers.pma.tls=true"
      - "traefik.http.routers.pma.tls.domains[0].main=pma.local"

volumes:
  db_data:

networks:
  web:
    external: false